server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/xjch/springcloudconfigserver.git
          username: xjch
          password: 77032556xjch
          searchPaths: '{profile}'
      #配置仓库的分支
      #label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/